### ISSUE TITLE
catkin build faleid on OpenCV v4xx

### ISSUE THREAD

**Issue by arnaldojr** [gsilano/rotors_simulator#2]
hello, 
I'm trying  to catkin build with ROS Melodic and OpenCV4.1.1 ubuntu18. Below the result:

![catkin1](https://user-images.githubusercontent.com/6247791/79780301-13058400-8312-11ea-9ae3-70236d84c4f8.png)

I find one solution: 

I replaced `CV_LOAD_IMAGE_GRAYSCALE` to `cv::IMREAD_GRAYSCALE` on ~/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp

the result catkin build:
![Screenshot from 2020-04-20 14-22-26](https://user-images.githubusercontent.com/6247791/79780814-e0a85680-8312-11ea-9653-95b97f19659a.png)

I think there will be no problems with other opencv versions.

**Comment by gsilano** [comment]
Hello! If the problem concerns [RotorS](https://github.com/ethz-asl/rotors_simulator) you should open an issue on the ETH repository. This is only a fork made for related projects such as [BebopS](https://github.com/gsilano/BebopS) or [CrazyS](https://github.com/gsilano/CrazyS).

**Comment by arnaldojr** [comment]
Ok.I opened it here because I tried to build your BebopS. I will open this issue on the ETH repository.  Thanks!
