### ISSUE TITLE
rotors_gazebo_plugins:make error

### ISSUE THREAD

**Issue by NoemiF99** [gsilano/rotors_simulator#3]
![Immagine 2023-09-22 183752](https://github.com/gsilano/rotors_simulator/assets/145793961/26ac78cc-7320-4464-baa1-7bbd6051f7d9)
![Immagine 2023-09-22 183710](https://github.com/gsilano/rotors_simulator/assets/145793961/55416142-97a8-4fb0-ac56-2a16e7af88bf)
![Immagine 2023-09-22 183633](https://github.com/gsilano/rotors_simulator/assets/145793961/ad65326e-1569-448f-a401-195983308587)
How can I solve this problem?

**Comment by gsilano** [comment]
Please close and then reopen this thread within the [CrazyS repository](https://github.com/gsilano/CrazyS). This will help streamline issue tracking. Thank you!
